---
title: "Muscle Samples"
author: "Caroline Sutton"
date: "2023-10-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#Load libraries
library(tidyverse)
library(knitr)
library(dplyr)

tissues_all <- read_csv("data/IN2023V05_TissueSamples.csv")
sites_P <- read_csv("data/Sites_P.csv")
tubes <- read_csv("data/IN2023V05_Isotope_Tubes.csv")
tubes <- tubes %>% 
  rename("TISSUE" = `Tissue barcode`)%>% 
  mutate(TISSUE = as.numeric(TISSUE)) %>% 
  rename("Tube_no" = `tube number`) %>% 
  rename("Box_no_assamplebag" = `Box number (as written on the sample bag)`)
  
cc <- read_csv("data/catchcomp.csv") 
```

## Match data to tubes
```{r}
cc <- cc %>% 
  select(SPCODE,SCIENTIFIC_NAME,COMMON_NAME) %>%
  distinct()

tissues_all <- tissues_all %>% 
  select(SPCODE,SITE_ID,LENGTH_MM,TISSUE,BIOLOGICALS_COMMENTS) %>% 
  left_join(cc, by = "SPCODE") 

tubes <- tubes %>% 
  filter(TISSUE != is.na(TISSUE))
  
  
```

### Priority samples
```{r}
sites_P <- sites_P %>% 
  mutate(choose = "y")

Tissues_priority <- tissues_all %>% 
  # choose priority sites
  left_join(sites_P, by = "SITE_ID") %>% 
  filter(choose == "y") %>% 
  # choose priority spcecies
  filter(SPCODE == 37296001 | SPCODE == 37445006 | SPCODE == 37439002 | SPCODE == 37038004 | SPCODE == 37287001 | SPCODE == 37228002| SPCODE == 37465006| SPCODE == 37330014| SPCODE == 37227001)

write_csv(Tissues_priority, "results/SEAMES_IN2023V05_PriorityIsotopeSampeles.csv")

# check selection
#distinct(Tissues_priority,COMMON_NAME)
```

### Tube samples
```{r}

#add scientific name
tubes <- tubes %>%
  left_join(tissues_all, by = "TISSUE") %>% 
  filter(TISSUE != is.na(TISSUE)) %>% 
  arrange(Tube_no) 

# add size catagory
tubes<- tubes %>% 
  mutate(Species_size = ifelse(SPCODE == 37296001 & LENGTH_MM >=300, "Platycephalus richardsoni_lg",SCIENTIFIC_NAME)) %>% 
    mutate(Species_size = ifelse(Species_size == 'Platycephalus richardsoni', "Platycephalus richardsoni_sm",Species_size))

tubes_1 <- tubes %>% 
  select(TISSUE,Tube_no,SPCODE, SITE_ID,LENGTH_MM,SCIENTIFIC_NAME,COMMON_NAME,Species_size)

write.csv(tubes_1,"results/SEAMES_IN2023V05_isotopetubes.csv")
write.csv(tissues_all,"results/SEAMES_IN2023V05_Tissues_All.csv")
```

### match Tissues to species 
```{r}
TissueData <- tissues_all %>% 
  left_join(cc)
```
