---
title: "trophic and isotope-zone"
author: "sutton"
date: "2024-12-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(knitr)
```
load data
```{r}
#"C:\Data Focus\RProjects\SEA_MES\data\20240801_V_INVERTEBRATE_CATCH_2_sponges.csv"
#"C:\Data Focus\RProjects\SEA_MES\data\Invertebrate_sponge_subsampling_241224.csv"
iso <- read.csv("X:/work/Taxonomy/Sampling Inventories/IsoZones.csv")
zones <- read.csv("X:/work/Taxonomy/Sampling Inventories/zones.csv")

#isotope data
results <- read_csv("data/isotopes/invert_iso_results.csv")
cephs <- read_csv("data/isotopes/ceph_tissue.csv")
krill <- read_csv("data/isotopes/krill_tissue.csv")
prawn <- read_csv("data/isotopes/prawn_tissue.csv")

```


ISOTOPE RESULTS


need survey_op data for cephs
select feilds
```{r}
colnames(cephs)
colnames(iso)

#get survey_ops
iso_ops <- iso %>%
  mutate(BARCODE = as.numeric(BARCODE)) %>% 
  select(BARCODE,Survey_Ops) %>% 
  distinct(BARCODE, .keep_all = TRUE)

colnames(iso_ops)

cephs_1 <- cephs %>%
  drop_na(Tubeno) %>% 
  filter(Tubeno != "x") %>% 
  mutate(sample_ID = Tubeno) %>% 
  mutate(TubeID = Tubeno) %>% 
  left_join(iso_ops, by = "BARCODE") %>% 
  mutate(type = "ceph") %>% 
  select(sample_ID,TubeID, type,Survey_Ops,SITE_ID, zone, Length = ML_mm,sex)
  
results <- results %>% 
  mutate(Lab = "csiro")
```



conform invert metatdata
```{r}
krill_1 <- krill %>% 
  mutate(sample_ID = Tubeno) %>% 
  mutate(TubeID = Tubeno) %>% 
  mutate(type = "krill") %>% 
  select(sample_ID, TubeID,type,Survey_Ops = Survey_ops)
  

prawn_1 <- prawn %>% 
  mutate(
    sample_ID = TubeID,
    Length = as.numeric(CL_mm),
    type = "prawn") %>% 
  select(sample_ID, TubeID, type,Survey_Ops,  SITE_ID, zone = Zone,Length)

```
stack invert metatdata
```{r}
colnames(krill_1)
colnames(prawn_1)
colnames(cephs_1)


tissue <- bind_rows(cephs_1, prawn_1,krill_1)

```

add tissue metadata to results

```{r}
colnames(tissue)
colnames(results)

results_inverts <- results %>% 
  left_join(tissue, by = "sample_ID")
```



```{r}
colnames(zones)
colnames(iso)
```

distinct values for Survey_Ops, Lat = ON_BOTTOM_USBL_BEACON_LATITUDE, Long = N_BOTTOM_USBL_BEACON_LONGITUDE)


```{r}

zones1 <- zones %>% 
  distinct(Survey.Ops,.keep_all = TRUE) %>% 
  select(Survey_Ops = Survey.Ops, Barcode, Lat = On.Bottom.Usbl.Beacon.Latitude, Long = On.Bottom.Usbl.Beacon.Longitude, Site_ID = Site.ID.voyage.specific.waypoint.grid., Zone, Ops, Voyage)

iso1 <- iso %>% 
  distinct(Survey_Ops, .keep_all = TRUE) %>% 
  select(Survey_Ops,barcode_tissue.1, Site_ID = SITE_ID, Tube_NO,Tube, zone, iso_group)
```

join datasets

```{r}

# left_join(d1, d2, by = c("x" = "x2", "y" = "y2"))

ZonesIso <- left_join(zones1,iso1, by = "Survey_Ops") %>% 
  mutate(test = ifelse(Zone == zone, 1,0))

```
Write dataset

```{r}
write.csv(ZonesIso, "X:/work/Taxonomy/Sampling Inventories/SEAMESZoneIso.csv")
```
